version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studypage-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/studypage
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - FLASK_ENV=production
      - DEPLOY=true
    volumes:
      # Mount code for development (remove in production)
      - ./backend:/app
      # Persistent uploads directory
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - studypage-network

  db:
    image: postgres:15-alpine
    container_name: studypage-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=studypage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - studypage-network

volumes:
  postgres_data:

networks:
  studypage-network:
    driver: bridge

