"""Add is_ai_free field to Expert model

Revision ID: 1b00ef105c6c
Revises: 85f6af0e48ee
Create Date: 2025-01-11 09:56:51.029156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b00ef105c6c'
down_revision = '85f6af0e48ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.drop_column('is_ai_free')

    # ### end Alembic commands ###
