"""Add attachments to messages

Revision ID: 53e58854e52d
Revises: 02ab30bef7e6
Create Date: 2024-12-10 10:46:31.118205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e58854e52d'
down_revision = '02ab30bef7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###
