"""setup rating

Revision ID: 85f6af0e48ee
Revises: 24ccba468979
Create Date: 2025-01-03 22:50:53.039290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f6af0e48ee'
down_revision = '24ccba468979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('success_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.drop_column('success_rate')
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('rating_avg')

    op.drop_table('ratings')
    # ### end Alembic commands ###
