"""Update User Model

Revision ID: a8efc693db2d
Revises: 9448e1051bc5
Create Date: 2024-09-25 23:18:08.241445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8efc693db2d'
down_revision = '9448e1051bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('biography',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('education',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('project_types',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subjects',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.alter_column('subjects',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('project_types',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('biography',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
