"""Added project_type and subject relationships to ProjectRequest update

Revision ID: bc16e6b41e07
Revises: 95724ab63539
Create Date: 2024-10-08 02:19:03.090593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc16e6b41e07'
down_revision = '95724ab63539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.drop_column('attachments')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
